### ISSUE TITLE
Instagram API can not be installed on Mac

### ISSUE THREAD

**Issue by serdardalgic** [tikalk/commandcar#10]
I get this error when I try to install the instagram API:

``` bash
> sudo commandcar install --api instagram   
installing @commandcar/instagram
validateTree              - |####################################################################################---------------------------------------------------------------|
/usr/local/lib/node_modules/commandcar/node_modules/npm/lib/install/filter-invalid-actions.js:24
    if (pkg.isInLink || pkg.parent.target || pkg.parent.isLink) {
                                  ^

TypeError: Cannot read property 'target' of null
    at module.exports (/usr/local/lib/node_modules/commandcar/node_modules/npm/lib/install/filter-invalid-actions.js:24:35)
    at Array.<anonymous> (/usr/local/lib/node_modules/commandcar/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/commandcar/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/commandcar/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Object.Installer.computeLinked (/usr/local/lib/node_modules/commandcar/node_modules/npm/lib/install.js:411:41)
    at Array.<anonymous> (/usr/local/lib/node_modules/commandcar/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/commandcar/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/commandcar/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at module.exports (/usr/local/lib/node_modules/commandcar/node_modules/npm/lib/install/diff-trees.js:50:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/commandcar/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
```

npm version 3.3.9, commandcar@0.0.21.

Please ping me if you need more information.

**Comment by shaharsol** [comment]
This is no longer relevant with the new v0.1.1. P|ease have a look at the new version.

**Comment by serdardalgic** [comment]
Thanks, I'm checking it out now.
